Fix bug in JAX array initialization: Qs.set(0).set(P0) -> Qs.at[0].set(P0).
The current code fails with the following AttributeError:

    --> 240     Qs = Qs.set(0).set(P0)  # first element requires different initialisation
    AttributeError: DynamicJaxprTracer has no attribute set